### ISSUE TITLE
Links to YouTube videos no longer work

### ISSUE THREAD

**Issue by g126** [ibm-hyper-protect/ibm-hyper-protect.github.io#22]
Please consider new links to DTE website:

Getting Started with IBM Cloud Hyper Protect Crypto Services -https://mediacenter.ibm.com/id/0_z5c589ou

Getting Started with IBM Cloud Hyper Protect Virtual Servers - https://dw1.s81c.com/caas-storage/5Khi7XGf/_videos/Getting%20Started%20with%20IBM%20Cloud%20Hyper%20Protect%20Virtual%20Server.mp4

Getting Started with IBM Cloud Hyper Protect DBaaS - https://mediacenter.ibm.com/media/0_2wa8vkxt

**Comment by g126** [comment]
@chrispoole643 - please assign and review

Also included HPVS and HPCS tutorials

**Comment by chrispoole643** [comment]
Thanks Peter! Merged.
